### ISSUE TITLE
No error when incorrect Ferdi URL is put in

### ISSUE THREAD

**Issue by probablykasper** [getferdi/server#12]
I accidentally put an extra slash into the Server field when switching to the Ferdi server (so it was `https://api.getferdi.com/`). When signing in, this results in nothing happening at all, which means it's hard to tell what went wrong.

The console shows a 404 error as it tries to connect to a URL like `https://api.gerferdi.com//apiorwhatever`.

**Comment by vantezzen** [comment]
Fixing this server-side via a26ea30.
