### ISSUE TITLE
Disabling service result in 401

### ISSUE THREAD

**Issue by kytwb** [getferdi/server#13]
Request sent to the server when disabling a service is returning a 401:

> {"message":"Invalid POST arguments","messages":[{"message":"required validation failed on name","field":"name","validation":"required"}],"status":401}

**Comment by kytwb** [comment]
Related to:

https://github.com/getferdi/server/blob/a3e5b3ccf0d652428a6ef6f533925a2162c35a01/app/Controllers/Http/ServiceController.js#L182

**Comment by kytwb** [comment]
@vantezzen do we need the validation linked above?

**Comment by vantezzen** [comment]
Yes, but it looks like the validation is wrong. I‘ll check what the name or the parameter actually is.

**Comment by kytwb** [comment]
The endpoint seem to be used to update all sort of attributes of a service:

https://github.com/getferdi/server/blob/a3e5b3ccf0d652428a6ef6f533925a2162c35a01/app/Controllers/Http/ServiceController.js#L205

That's why I thought the validation wasn't needed. In that case, the request send  a payload that looks like `{isEnabled: true/false}` if I remember correctly.

**Comment by vantezzen** [comment]
Ok, just looked at it again and I think you are right - we can just delete this validation. I thought the name would be sent everytime but it doesn’t.

**Comment by kytwb** [comment]
@vantezzen Done! 👍 Could you please redeploy and/or document how-to redeploy when you have time please?

**Comment by vantezzen** [comment]
Just updated the server. You can update the server by running the `update.sh` script in `server/`.

Could you also add this fix to the internal server?

**Comment by kytwb** [comment]
Done via https://github.com/getferdi/internal-server/commit/48cb16fefe46ab66b1884f18e04c1f701a8e0c09.
