### ISSUE TITLE
Implement service recipe update

### ISSUE THREAD

**Issue by kytwb** [getferdi/server#14]
I have not worked on the server just yet but I am keen to take a look. That would be useful to be able to ship the fix for https://github.com/getferdi/ferdi/issues/140 and https://github.com/getferdi/ferdi/issues/229 smoothly.

**Comment by kytwb** [comment]
@vantezzen I think this could become useful; commenting to bump and bring back to attention.

**Comment by vantezzen** [comment]
We would then need to add functionality to Ferdi that will update from the most up-to-date source. Currently, Ferdi will always use the internal recipe repo.

**Comment by kytwb** [comment]
Iterated on this with https://github.com/getferdi/server/commit/e1cc68d8bf4d473307638607dfee98a90bc7a6be, https://github.com/getferdi/server/commit/a53d5f8ab5c089f0f8ab19125db4c6f7b4058373 and https://github.com/getferdi/server/commit/22b145e40a590330d717db687e8509fc446ac857.  
Successfully picked up https://github.com/getferdi/recipes/commit/e8a97c037dd0140222c9dd29e63a346616f29f83 with a tweak in the client.
