### ISSUE TITLE
Password doesn't get transferred correctly when importing Franz account

### ISSUE THREAD

**Issue by vantezzen** [getferdi/server#19]
Multiple users now reported that after importing their Franz account they can't login.

Looking into the database, it looks like all the data is there and imported - just the password isn't correctly hashed.

**Comment by vantezzen** [comment]
It looks like I can't reproduce this bug - neither locally nor on the Ferdi server. Everytime I import a Franz account I can login just fine.

**Comment by k0staa** [comment]
This one is currently blocked by [https://github.com/getferdi/server/issues/19](https://github.com/getferdi/server/issues/19)
