### ISSUE TITLE
Server database and install process

### ISSUE THREAD

**Issue by xthursdayx** [getferdi/server#2]
Forgive my ignorance, but when trying to install this I see that it is currently set up with SQLite for the database. Does that mean that I need to install SQLite (with the code `npm i sqlite3`) and set up the database before I run `adonis migration:run`? 

Or, if say I want to use MariaDB, is it as simple as running `npm i mysql`,  creating the database, and updating the .env file, or is there anything else I need to do to switch from sqlite to mysql?

Also, just so you know, I tried just installing the adonisjs cli and running `adonis migration:run` as the README.md says, but I ran into problems and had to install lucid (`npm i -g @adonisjs/lucid`). However, I then found that the migration was still not working. In fact, `adonis migration:run` was not being recognized at all, so I had to run `node ace migration:run`. 

Can you clarify what I'm doing wrong? Thanks!

**Comment by vantezzen** [comment]
Normally you should be able to simply run `adonis migration:run` after installing local dependencies and AdonisJS will automatically set up the SQLite database itself. As `sqlite3` [is already a dependency](https://github.com/getferdi/server/blob/master/package.json#L37) there should normally be no reason to install it separately.
Have you run `npm install`?

When using MariaDB or PostgreSQL the workflow you described should work: Simply install its package, create the database and update the .env file and run the migrations. Additional info can be found [in the AdonisJS documentation](https://adonisjs.com/docs/4.1/database#_supported_databases).

Your problem looks like you might not have run `npm install` to install local dependencies. Unfortunately I've forgot to add it to the readme but added it now.

**Comment by xthursdayx** [comment]
Okay, cool. I'll give that a try. FYI the original error I was getting when trying to run `adonis migration:run` was `error: `migration:run` is not a registered command`. 

BTW, I'm in the process of trying to create a stable docker container for Ferdi-server, so once I get it working I'll let you know, in case you want to link to it.

**Comment by xthursdayx** [comment]
@vantezzen your suggestion about npm install was correct.

So you know, I've gotten a dockerized version of ferdi-server up and running. If you're interested I can share the link.

**Comment by vantezzen** [comment]
Great! Yes, I'd be interested.

**Comment by xthursdayx** [comment]
Cool, here is my repo: https://github.com/xthursdayx/ferdi-server-docker 

I'm happy to link it up with the project more directly if there is a way to do so.

**Comment by vantezzen** [comment]
@xthursdayx Thank you for publishing your project. I took a look at your Dockerfile but still have some questions (Sorry, I am not too familiar with creating Docker images so excuse me when some questions are beginner questions):
- Why do you [install yarn](https://github.com/xthursdayx/ferdi-server-docker/blob/e55257f929715fdaff5b2c72d69b4db2adcd98ef/Dockerfile#L80) when ferdi-server only uses npm?
- It looks like you set an [`APP_DIR`](https://github.com/xthursdayx/ferdi-server-docker/blob/e55257f929715fdaff5b2c72d69b4db2adcd98ef/Dockerfile#L8) variable but [don't actually use it](https://github.com/xthursdayx/ferdi-server-docker/blob/e55257f929715fdaff5b2c72d69b4db2adcd98ef/Dockerfile#L88) ([also in root/etc](https://github.com/xthursdayx/ferdi-server-docker/blob/e55257f929715fdaff5b2c72d69b4db2adcd98ef/root/etc/cont-init.d/50-config#L51)). Is this intended?
- Why did you choose to base your Dockerfile on `lsiobase/alpine` instead of [`node`](https://hub.docker.com/_/node)(which also has an alpine-based version and npm-preinstalled)?
- You seem to [add a new user abc](https://github.com/xthursdayx/ferdi-server-docker/blob/master/root/etc/cont-init.d/10-adduser) - what is this user used for?

Also, it looks like you still [have an issue with creating the env file](https://github.com/xthursdayx/ferdi-server-docker/issues/1).

**Comment by Ryonez** [comment]
He probably;y wants to use [S6-Overylay](https://github.com/just-containers/s6-overlay) (A process supervisor).
The abc user is something I've seen linuxserver use a *lot* in their images.

If I'm to guess he's probably new to this and is trying to follow what a very successful group does. I'd be doing the same when I get around to making some of my own images.

Also nice to notice PUID and GUID are settable. That's not documented.

**Comment by xthursdayx** [comment]
Hey @vantezzen thanks for your interest in the docker image I put together. @Ryonez is right on pretty much all counts. To begin with, I'll say that I'm still pretty new at this, so please excuse any errors. Most of what I know about Linux, Docker, etc, I learned over the last few years, in service of running software I'm interested in, in ways that I want, on my own server. As a result, my knowledge can be somewhat patchy, in that my approach to learning is pragmatic and utilitarian.

I decided to use the lsiobase/alpine base image because I tried to create an image using both the normal node base image and the node-alpine image, with an entry-point start-up script, and kept running into problems with ferdi-server's files not being copied correctly or being overwritten during the initial run of the container, and with ENV variables being lost. Because of this, I decided to use alpine + S6 Overlay to manage my ENV variable persistence and the actual launching of ferdi-server. I started to work on creating an image combining Alpine + Node + S6, but then realized that Linuxserver's Alpine base image already has the S6 Overlay included and so decided to just go with that, since I'm already quite familiar with and trust their work. 

You're right about APP_DIR - I used the $APP_DIR in earlier versions of the Dockerfile, but ended up not using it in the interest of keeping the file structure visible, since I changed things around quite a bit. I'll remove it from the Dockerfile. 

I guess that I can remove the yarn install lines from the Dockerfile, I included them because I I took my Node install code from the official Node docker image and wasn't sure if yarn necessary for anything else Node-related. 

In terms of the abc user, I set it because this is the user:group that is set and used in the lsiobase image, so I wanted to be consistent. 

I'm going to look into the issue @Ryonez found with the database ENV variables being ignored. 

Any other thoughts or suggestions are welcome and appreciated. Cheers.

**Comment by vantezzen** [comment]
@xthursdayx Thank you for answering my questions. Your docker image looks very useful for people who want to set up a ferdi server.

Is there a way we can get your docker image to the [getferdi organization on Docker Hub](https://hub.docker.com/u/getferdi)? Should I add you to that organization?

**Comment by xthursdayx** [comment]
@vantezzen Sure, I'm not sure how that works exactly, but add me to the org and I'll see about getting it loaded once I sort out the database ENV issue.

**Comment by vantezzen** [comment]
Added you to the Docker org. Just write here if I need to also add you to the GitHub org.

**Comment by xthursdayx** [comment]
@vantezzen it looks like I've fixed the ENV issues and the docker image is stable now. I just had a look at the docker hub org and created a repo for the ferdi-server docker, but I think it will be easier if you add me to the GitHub org as well for future updates to the base code. Cheers.

**Comment by vantezzen** [comment]
Just send your invitation to the GitHub org.

**Comment by xthursdayx** [comment]
Thanks, but can you change my status in the Github org to owner instead of member? Apparently I need to be an owner in order to link the server-docker github repo to the Docker hub repo. Alternatively you can log into Docker Hub and I believe that you should be able to link the Docker Hub org to the Github org.

**Comment by vantezzen** [comment]
I now set up a separate @FerdiBot user to link Docker Hub to, as [suggested by the Docker docs](https://docs.docker.com/docker-hub/builds/#service-users-for-team-autobuilds)

**Comment by xthursdayx** [comment]
Great, thanks, that works. I found the Docker docs a bit confusing on that point, which is why I tried creating a build team within the Github org and adding myself to it first.
