### ISSUE TITLE
Add option to disable users registration

### ISSUE THREAD

**Issue by zichichi** [getferdi/server#21]
I have exposed my ferdi server, active on docker, on the internet and I would like to disable the registration of new users. I tried to set the IS_CREATION_ENABLED = false and ONNECT_WITH_FRANZ= false but I can create new users

**Comment by vantezzen** [comment]
`IS_CREATION_ENABLED` only disables that users can upload new recipes. This would be a new feature request.

**Comment by vantezzen** [comment]
Added new option `IS_REGISTRATION_ENABLED` with v1.0.3

**Comment by zichichi** [comment]
Thanks for your help.
Would it be possible to put the variation on your docker container? Thank you.

**Comment by vantezzen** [comment]
Just triggered a new Docker build which should be done in a few minutes.
