### ISSUE TITLE
persistent data sqlite whit docker

### ISSUE THREAD

**Issue by garffi** [getferdi/server#26]
Hello,
I do not understand why I come up against this problem of data persistence of the sqlite database.

I configured a patch like this:
-v /mnt/docker/ferdi/db:/usr/src/app/database

But the persistence of the database is not achieved.
The rest works, thanks

**Comment by carroarmato0** [comment]
I have the same issue when the container is stopped and removed.

It looks like the sqlite database is not stored in the documented path

**Comment by carroarmato0** [comment]
And since it's a bug in the docker image, should go to https://github.com/getferdi/server-docker/issues

**Comment by xthursdayx** [comment]
I merged the PR @carroarmato0 created in the ferdi-server docker repo: https://github.com/getferdi/server-docker/pull/5

The documentation hadn't been updated after a previous update to the Dockerfile, thanks for catching it!
