### ISSUE TITLE
Add dynamic "Popular Services" list

### ISSUE THREAD

**Issue by SanketDG** [getferdi/server#27]
**Describe the bug**

**To Reproduce**

-  Open Ferdi
- Click on Add Service
- Click on Inbox on Most Popular Services
- Nothing happens

**Expected behavior**
Inbox should be replaced with some other application

**Desktop:**

- OS: Linux
- Ferdi Version: 5.5.0

- Server Used: https://api.getferdi.com

**Comment by SanketDG** [comment]
@vantezzen I can take this up  if you want, what controller in the API code should I be looking for?

**Comment by vantezzen** [comment]
Awesome! Here's what would have to be done:

- Our recipes are stored in <https://github.com/getferdi/recipes/blob/master/all.json> so you will somehow need to import that repository. I suggest you do the same thing we did with the Ferdi repository and simply add the recipe repository as a git submodule like:

```Bash
git submodule add https://github.com/getferdi/recipes recipes
```

You will then have the file in `/recipes/all.json`.

- The `all.json` file contains objects with a "`featured`" attribute so you'll need to filter out all recipes that are featured.

- The current code for the popular recipes list is in https://github.com/getferdi/server/blob/master/app/Controllers/Http/StaticController.js#L99

**Comment by SanketDG** [comment]
Great, thanks for the quick explanation.

Is there some sort of metric that I should use to mark certain applications as "featured"? 
Or should I just go with the current list of applications that are shown in "Most Popular"?

Also, as a suggestion, we could use the anonymous telemetry data to figure out the most popular services that are being used through Ferdi.

**Comment by vantezzen** [comment]
I'd suggest we use the same services Franz is suggesting for now - we can further customize that in the future though
