### ISSUE TITLE
Deploy an instance of Ferdi server

### ISSUE THREAD

**Issue by kytwb** [getferdi/server#3]
Following discussion in https://github.com/getferdi/ferdi/issues/70.

**Comment by vantezzen** [comment]
I'd suggest deploying it under `api.getferdi.com`.

**Comment by vantezzen** [comment]
So it looks like we would need a AWS EC2 and a RDS instance to deploy Ferdi server. 
Both would be free in the first 12 months of an AWS account - is your account still in that period by any chance? Unfortunately mine isn't anymore.

**Comment by vantezzen** [comment]
> In the meantime, I'm happy to provide access to an EC2 instance if you want to start taking a look at it, just let me know.

It looks like it would be best to run the server on [AWS Elastic Beanstalk](https://aws.amazon.com/getting-started/tutorials/launch-an-app/) on one EC2 and one RDB instance - which should be included in the free tier. Could you provide those?

**Comment by kytwb** [comment]
@vantezzen can provide those too 👍 let's catch up on this during our call later this week.

**Comment by kytwb** [comment]
Following-up from our call, we will start with an EC2 instance and process manager (to make sure the app restart on failure) and a managed database (RDBS) so the backups are taken care of.

**Comment by kytwb** [comment]
@vantezzen Sent a secured note via Dashlane including the EC2/RDS credentials.

**Comment by vantezzen** [comment]
Ok. I don't use Dashlane so I just created a new account but I don't see the shared note. Is there anything I still have to do?

**Comment by vantezzen** [comment]
Ok, got it now. Could you point `api.getferdi.com` to the EC2 server so I can create a LetsEncrypt certificate?

**Comment by kytwb** [comment]
@vantezzen sorry for following-up just now. Glad you managed to get the note; I have now pointed api.getferdi.com to the EC2 instance.

**Comment by vantezzen** [comment]
No problem. I do however get a 522: Connection timeout when trying to connect to `api.getferdi.com` and trying to generate the SSL certificate, same when trying to connect EC2 to the database.

Also, could you still give me write access to the Dashlane Note?

**Comment by kytwb** [comment]
@vantezzen should be all taken care of.

**Comment by vantezzen** [comment]
Should be set up and ready to go now. I also updated the default API server of Ferdi to our new API (938d519).

**Comment by kytwb** [comment]
@vantezzen well done! 💪
