### ISSUE TITLE
Can't import Franz account

### ISSUE THREAD

**Issue by wolfwm** [getferdi/server#36]
**Bug description:**
When trying to import my Franz account through https://api.getferdi.com/import, I'm shown the following message: Could not login into Franz with your supplied credentials. Please check and try again.
I have checked, and this account is active and working on Franz with the submitted credentials.

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/28539406/90698709-ce560f00-e257-11ea-845c-308e88021e38.png)

**Environment:**
- Operating System: Windows 10 and Manjaro Linux
- Ferdi Version: Ferdi website (accessed through Brave browser and Chrome browser)
- Server: Franz

**Comment by gburning** [comment]
Likely the same as https://github.com/getferdi/ferdi/issues/927
