### ISSUE TITLE
Docker File volumes seem to be wrong in the documentation

### ISSUE THREAD

**Issue by swcurran** [getferdi/server#43]
I'm trying out self-hosted Ferdi Server, and I found that the docker instructions seem to have a problem.   The volume lines (e.g. `/usr/src/app/database` and `/usr/src/app/database/recipes` should reference `/apps`, not `/usr/src/app`.

When I ran as is, restarting the container lost the account database  I logged into the container while running and found the data in the /app folder, but since it wasn't the volume, it was not persisted.

 After I changed the paths, all worked. 
 
 Happy to do a pull request if a change is needed.

**Comment by vantezzen** [comment]
@xthursdayx

**Comment by xthursdayx** [comment]
@vantezzen the documentation is correct in the https://github.com/getferdi/server-docker/ readme, but hasn't been updated on the main server repo. I don't have editing privileges for this repo, so just created this pr: https://github.com/getferdi/server/pull/44
