### ISSUE TITLE
Dockerization

### ISSUE THREAD

**Issue by kytwb** [getferdi/server#5]
I was surprised that we created a repository just for the dockerization of the server https://github.com/getferdi/server-docker/ My guess is that we can add the Dockerfile directly in this repository. Also, if needed, we can add a docker-compose.yml file to help setup the database/nginx using pre-existing images (a-la https://github.com/jwilder/nginx-proxy). WDYT?

**Comment by vantezzen** [comment]
I think @xthursdayx would be the only to implement this. @xthursdayx What do you think about this idea?

**Comment by xthursdayx** [comment]
It would be possible, but would require either changing the file structure of the repo to suit the docker image as it currently runs, which doesn’t really make sense for the other non-docker users, or creating two folders in the root of the repo, one called `ferdi-server` with all of the existing code and one called`docker` with all of the build files (such as is done in this repo: [https://github.com/matrix-org/synapse](https://github.com/matrix-org/synapse)). This second option would make for a cleaner solution, but would necessitate a rewrite of the README.md to modify the instructions for a normal install to suit the new file structure. I’m not positive about if/how this new file structure would work with Docker Hub’s automated cloud builder, but I can look into it.

My gut feeling is that the two independent repos are easier to manage, but I’m happy to look into combining the two in more detail  of that is what you guys would prefer.

**Comment by kytwb** [comment]
@xthursdayx No problem then, let's keep things how they are and let's eventually refactor next time we get to work on the server Dockerization, if/when that makes sense.

**Comment by 1k-off** [comment]
Also, please, migrate all install directly to dockerfile. I get frustrated when I run container and must wait for npm installation and other preparation things. That must be done on build. Let me know, if you need help with this.

**Comment by xthursdayx** [comment]
@1k-off You might want to check out this PR: https://github.com/getferdi/server/pull/48

If you're interested in building the PR-version of the container and trying it out before I merge the PR, I'd welcome the additional testing.
