### ISSUE TITLE
Services not showing up in the 5.5.0

### ISSUE THREAD

**Issue by TanZng** [getferdi/server#52]
Problem fetching services from Ferdi 5.5.0 https://github.com/getferdi/ferdi/issues/861
This is the network when fetching the Services:
![image](https://user-images.githubusercontent.com/25267490/114050212-b0263900-9851-11eb-9d61-cb34ccdc440c.png)

Preview:
/root/server/officialrecipes/recipes/all.json: ENOENT: no such file or directory, open '/root/server/officialrecipes/recipes/all.json'

And some icons on "All services" are not found:
![image](https://user-images.githubusercontent.com/25267490/114050248-b87e7400-9851-11eb-8981-eaaa9cbe175f.png)

**Comment by vraravam** [comment]
@TanZng - unfortunately, we are no longer able to support/troubleshoot v5.5 of Ferdi. Please move to the latest nightlies that are themselves quite stable. The nightlies can be found [here](http://github.com/getferdi/nightlies/releases)
