### ISSUE TITLE
Import configuration a file with workspaces results in a (broken?) import

### ISSUE THREAD

**Issue by MartinX3** [getferdi/server#72]
I used ferdi without an account and wanted to import my data into the account.
I used workspaces.

`Could not import your workspaces into our system. Error: TypeError: workspace.services.map is not a function.`

Also it seems it imported my data halfway until it found the first workspace.

After removed the workspace from my local ferdi and exported the configs again, I was able to import my messengers, but now I have duplications.

**Comment by vraravam** [comment]
The import logic needs to accommodate atomic transactions if the import failed half-way while processing.

**Comment by vraravam** [comment]
@MartinX3 - the latest version of the ferdi server was deployed in the past 24 hours. Please check if this bug is still replicatable.

**Comment by MartinX3** [comment]
Sadly it's hard to test for me
Either I wipe my main account and the ferdi app, to create minimal test data to test with and hopefully being able to restore my main account backup later without getting trouble.

Or I get a new email address to make a new account and get a new computer to test a clean ferdi installation on it.

Do you have some kind of UNIT tests to test the server import code?

**Comment by vraravam** [comment]
@MartinX3 - I have been able to export from my remote hosted ferdi server into my local ("without server"). I have tested this in my developer profile (unpackaged Ferdi), as well as the packaged version of Ferdi. 
By unpackaged, I mean running from the source itself as a dev build.

If you want to try it out, you can always backup your whole ferdi profile folder, and then resurrect it back again after your testing completes.

**Comment by MartinX3** [comment]
If it works for you to restore workspaces, I'll trust you :)
Thank you for your hard work :)
