### ISSUE TITLE
Error Message: Could not validate custom GitHub server.

### ISSUE THREAD

**Issue by CepheidVariable** [getferdi/server#77]
When attempting to add a GitHub service the "Custom Server" field is required, but the default value of:

`https://github.com/notifications` 

returns the following error:

`Could not validate custom GitHub server.`

**Comment by vraravam** [comment]
@CepheidVariable - 
1. please log bugs against the getferdi/ferdi repo - not this one
2. I just tried with the latest nightly, and am unable to reproduce this bug.
