### ISSUE TITLE
Workspace configurations don't appear to save.

### ISSUE THREAD

**Issue by djshadowxm82** [getferdi/server#8]
**Describe the bug**
After a restart of Ferdi, All workspaces are present, however no services are assigned to them anymore.

**To Reproduce**
1. Setup workspaces and save
2. Restart  the application.
3. Empty workspaces.

**Expected behavior**
Workspaces to load as left.

**Screenshots**
![image](https://user-images.githubusercontent.com/10658965/67165466-35164d80-f353-11e9-9205-eeef6482945d.png)

**Desktop (please complete the following information):**

-OS: Microsoft Windows [Version 10.0.17763.805]
-Ferdi Version 5.4.0-beta.2 (x64)
-Electron 6.0.10
-Node.js v12.4.0
-Platform: win32

**Comment by vantezzen** [comment]
Fixed via 8962fb2. Your Workspaces did save but the server didn't send them in the correct format when reloading the application.
