### ISSUE TITLE
Maintain Tagged Docker Images

### ISSUE THREAD

**Issue by Ryonez** [getferdi/server#81]
Currently, only two docker tag are maintained, `latest` and `main`.

There should be tagged versions, based on the version of the server being used.

The lack of tagged versions has left me in a position where I updated to the latest version, and now my server is down. There are no breaking changes listed on dockerhub, but there most certainly is. One for example, is the change from using the `config` directory to `data` for the config dir.

Without those versions, I'm currently stuck with a non functional server.

**Comment by xthursdayx** [comment]
We are intending to put semantic versioning in place for the server docker image however this has not been implemented yet. Please check the [migration instructions here](https://github.com/getferdi/server/blob/master/docker/README.md) to see if that will help you get your ferdi-server running again. The new image works fine with the migration parameters in place.

**Comment by xthursdayx** [comment]
The semver tagged images are now up on Docker Hub.
