### ISSUE TITLE
Error: The server does not support SSL connections

### ISSUE THREAD

**Issue by Ryonez** [getferdi/server#82]
When trying to sign into the account dashboard with the latest docker image, the site responds with the message: `The server does not support SSL connections`
![image](https://user-images.githubusercontent.com/16157130/142285764-0499bc9f-9285-48a5-b17b-ec6aa8456f40.png)

I'm not aware of any settings related to this and any account interactions don't work. My desktop client cannot talk to the server due to this, i also get the same error (visible in the dev console).

The server was working with the previous version without issue.

**Comment by xthursdayx** [comment]
Please check to make sure that you are using all of the correct parameters as described [here](https://github.com/getferdi/server/blob/master/docker/README.md). Also check your NGINX configuration. I am using the same settings and NGINX block and am not having any problems accessing the account dashboard via https.

**Comment by Ryonez** [comment]
As far as I can tell my config is good:
![image](https://user-images.githubusercontent.com/16157130/142297274-8c3b7c91-2bb5-49e4-89b5-2ba69c2d0cb0.png)

Ngnix block should be good to. The site functioned before this, and still does still until I go to access the dashboard.

**Comment by Ryonez** [comment]
Ahh, and the only log thing I can find regarding this from the container:
![image](https://user-images.githubusercontent.com/16157130/142298038-2fc351b6-9811-43cb-8077-ddcfd230dafd.png)

**Comment by xthursdayx** [comment]
Please see my note here: https://github.com/getferdi/server/issues/79#issuecomment-972227179

This problem is the result of you setting the `APP_URL` variable to `https` rather than the local address `http://ip:port`. For security reasons we don't support running Ferdi-server exposed to the external internet directly. You should use a reverse proxy such as NGINX to connect your subdomain `ferdi.alteria.xyz` via to `https` to your local `http://ip:port`.

**Comment by Ryonez** [comment]
Looking at that log I figured it out, an undocumented change for the variable `SSL` to `DB_SSL`.

I recommended the migration guides go over just the things that have changed to help avoid this in the future. The majority of that guide just repeated some setup variables, rather than address the actual changes.

**Comment by Ryonez** [comment]
> Please see my note here: [#79 (comment)](https://github.com/getferdi/server/issues/79#issuecomment-972227179)
> 
> This problem is the result of you setting the `APP_URL` variable to `https` rather than the local address `http://ip:port`. For security reasons we don't support running Ferdi-server exposed to the external internet directly. You should use a reverse proxy such as NGINX to connect your subdomain `ferdi.alteria.xyz` via to `https` to your local `http://ip:port`.
> 
> The variable `EXTERNAL_DOMAIN` is used to tell Ferdi-server what external https domain (or subdomain) you'll connect to the server with.

Unrelated (this was in place and working before the docker change), and the server is secured behind a proxy. The APP_URL  was manually set as the server kept using the incorrect url with clients.

**Comment by Ryonez** [comment]
Imma close this as the SSL error has been diagnosed and corrected now.
