### ISSUE TITLE
Default `DATA_DIR` is Invalid

### ISSUE THREAD

**Issue by Ryonez** [getferdi/server#84]
The template I use on unraid updated today and added a `DATA_DIR` variable with the default value `data`. This caused my container to break. 

Changing the value to `/data` corrected this.

**Comment by Cyboc** [comment]
I got a similar problem. My server uses an external database, but the app-key needs the `/data` directory, which is documented as for the sqlite database only. Do I need to mount that volume anyway or how can I fix this?

**Comment by Ryonez** [comment]
For some reason removing the `DATA_DIR` variable results in the container using the correct data directory, which is `/data`. 
And yes you do need to set a volume pointing to that directory for the app key, otherwise it'll generate an error and create a random app key which resets on restarting the container (I believe, not 100% on the resetting part).

**Comment by xthursdayx** [comment]
> I got a similar problem. My server uses an external database, but the app-key needs the `/data` directory, which is documented as for the sqlite database only. Do I need to mount that volume anyway or how can I fix this?

The `DATA_DIR` variable doesn't mount anything, only tells Ferdi-server where your database is located if you use sqlite and where the `FERDI_APP_KEY` text file should be saved. As @Ryonez said, you should then mount a host diirectory to `/data` as that is where you `FERDI_APP_KEY.txt` will be saved. This app key is created when you first start the container, but is not reset after that. 

If you are migrating from an existing Ferdi-server instalation using the old variables you can refer to the migration instructions posted [here](https://github.com/getferdi/server/tree/master/docker) and in the [UNRAID forums](https://forums.unraid.net/topic/83813-support-xthursdayx-ferdi-server/?do=findComment&comment=1055240). In a nutshell, you'll need to set the `DATA_DIR` variable to `/app/database/`, and mount `/app/databases` to the host directory where your app key file is (this should be how your container was previously set up). If you're migrating an existing container and are using an external database, then you won't need anything mounted to `/data`.

**Comment by xthursdayx** [comment]
> The template I use on unraid updated today and added a `DATA_DIR` variable with the default value `data`. This caused my container to break.
> 
> Changing the value to `/data` corrected this.

This was an error in the template. It should be fixed now. The correct entry for the variable `DATA_DIR` should be `/data` for a new (not migrated) installation.
