### ISSUE TITLE
Implement custom service icons

### ISSUE THREAD

**Issue by pztrn** [getferdi/server#9]
When trying to set custom icon for service loaded with custom website recipe and when using self-hosted ferdi-server I've got "There were errors while trying to perform an authenticated request" and icon isn't saved.

I'm on 5.3.3 and macOS 10.15.

<img width="241" alt="изображение" src="https://user-images.githubusercontent.com/869402/67349207-bb53af00-f560-11e9-940e-c840015b2561.png">

**Comment by vantezzen** [comment]
Custom service icons are not currently implemented into ferdi-server, but I'll add it in the next days.

**Comment by pztrn** [comment]
Thanks!

Can docker image be updated with this commit, please?
